source 'https://rubygems.org'

gem 'jekyll',           '~> 3.9.5'
gem 'jekyll-theme-hacker'
gem 'rouge',            '>= 3.11.0'
gem 'wdm',              '>= 0.1.0'
gem 'kramdown-parser-gfm'
gem 'webrick'

# Ruby 3.4 compatibility gems
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'logger'
gem 'mutex_m'
gem 'strscan'
gem 'forwardable'
gem 'monitor'
gem 'timeout'
gem 'date'
gem 'pathname'
gem 'tempfile'
gem 'tmpdir'
gem 'fileutils'
gem 'find'
gem 'rexml'